### ISSUE TITLE
ENHANCE: Website Content

### ISSUE THREAD

**Issue by AngelNull** [AngelNull/transrights#1]
# Enhancing Website Content
This website currently is missing some key information that could definitely be very helpful to provide to users. The next release should include multiple pages with more information on each one, and adding a navbar to support this change.

Some new information that could be added includes

- Additional Petitions;
- Charities & Support Groups;
- Protesting Guide & Dates in the UK;
- YouTube Videos; 
- Writing to MPs/The PM, including letter templating;
- Funding Links 
- Resources For Trans* People

## Additional Petitions 
All petitions will have to be sourced directly from [the official parliament petitions site](https://petition.parliament.uk), as they will not respond to petitions that are made elsewhere. 

New petitions that can be added:
- [Uphold current legal protections for transgender individuals and under 18s ](https://petition.parliament.uk/petitions/318175) / `Petition 318175`
- [Allow the display of LGBT+ pride flags without council permission](https://petition.parliament.uk/petitions/332509) / `Petition 332509`
- [Update gender identity guidance for schools to support students](https://petition.parliament.uk/petitions/553681) / `Petition 553681`

## Charities & Support Groups 
The charities and support groups portion of this page can include IRL charities and online support groups such as verified Discord servers and IRC chatrooms, this do not need to be UK specific.

| Charity/Support Group | Link                                 | UK Only |
|--------------------|--------------------------------------|---------|
| Mermaidsuk         | https://mermaidsuk.org.uk/           | Yes     |
| Stonewalluk        | https://www.stonewall.org.uk/        | Yes     |
| WeExist            | https://www.weexist.co.uk/ | Yes     |

**All communities listed should be used with own personal discretion**

| Community Name | Link                                 | UK Focused |
|--------------------|--------------------------------------|---------|
| LGBTQ+ Hangout     | https://www.discord.gg/pride         | No      |
| Gaymers | https://www.discord.gg/gaymers | No |
| r/TransgenderUK | https://www.reddit.com/r/transgenderuk | Yes | 
| r/Trans | https://www.reddit.com/r/trans | No| 

## YouTube Videos: 
Youtube videos are incredibly useful as a source of information as they can provide information in an infographical format which is more useful to people who struggle to read long amounts of text or find videos easier to digest.

- [How to Be a Good Trans Ally by Daily Hive](https://youtu.be/gP7FtvdYOlk)
- [6 Easy Ways to be a Good Trans Ally - Trans Talk | Episode 2](https://www.youtube.com/watch?v=n5LGDjmH9bg)

## Writing to MPs/The PM
Writing to MPs is a very good way of getting your voice heard, even if they do not directly acknowledge it, it will certain make an impact if enough people do it, which is what this will attempt to encourage. 

- [Kite Trust - Writing to your MP](https://www.thekitetrust.org.uk/write-to-your-mp/)
- [Stonewall Guide For Writing to MPs](https://www.stonewall.org.uk/node/75701)
- [MermaidsUK Guide](https://mermaidsuk.org.uk/news/write-to-your-mp/)

## Funding Links 
Funding links for charities in the trans* space and also for individuals in need of finacial support can be given their own page dedicated with a bunch of links and details for each one of them, and this can be updated monthly or so to ensure all links are current. 

## Resources For Trans* People
A lot of the resources on this website are dedicated to allies only, but some content on this website should be for trans* people trying to find more resources for themselves, such as protesting guides and places where they can find support and feel welcome. This content can likely be found through charity websites like MermaidsUK and more.

**Comment by angelicaldev** [comment]
Notes on this issue:

- Website is moving away from singlepage design to multipage
- References to issue creation and suggestions now have their own page 
- Each page will follow the same format, but with different content and resources for allies and trans* people have been split into 2 different sections with anchor points.
- Colour scheming is being updated; and maybe moving the website to default light theme, although not certain.
